### ISSUE TITLE
Kicking people from group chat doesn't decrease "and more" counter

### ISSUE THREAD

**Issue by ValdikSS** [subrosa-io/subrosa-client#44]
After kicking people from group chat, there is "4 more" element, while nobody is in group chat, except myself.

![3](https://cloud.githubusercontent.com/assets/3054729/5651008/cdafd6b6-96b4-11e4-848d-ea0a2a6563d6.png)

**Comment by ixro** [comment]
Thank you, fixed in 74ebee09b54275a374468ae4ff0a80449b3f679b!
