### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by balajibandi** [subrosa-io/subrosa-client#45]
npm install
npm WARN package.json subrosa-client@1.02.0 No repository field.

> v8flags@1.0.8 install /root/b/subrosa-client/node_modules/gulp/node_modules/v8flags
> node fetch.js

|
module.js:340
    throw err;
          ^
Error: Cannot find module '/root/b/subrosa-client/node_modules/gulp/node_modules/v8flags/fetch.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
npm ERR! v8flags@1.0.8 install: `node fetch.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the v8flags@1.0.8 install script.
npm ERR! This is most likely a problem with the v8flags package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node fetch.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8flags
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.16.0-29-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /root/b/subrosa-client
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by ixro** [comment]
I've just `npm install`'d a clean repository fine.  Your npm appears to be slightly out of date.

I've pushed out a new package.json which will force v3.8.10 of gulp - it looks like you're hitting this issue: http://stackoverflow.com/questions/26592611/gulp-js-trouble-installing-cannot-find-module-fetch-js

After you update npm and `git pull`, please try `npm install` again and let me know if that fixes it.

**Comment by ginahagg** [comment]
I had the same error. After i installed gulp, i also added the repository info in the package.json file. Mine wasn't about v8 flags, but it was missing the repository info in package.json. So, I added 

"repository" : { 
   "type" : "git",
   "url" : "https://github.com/subrosa-io/subrosa-client"
 }

and it worked.

**Comment by ginahagg** [comment]
I installed gulp 3.8.10. And tried 'gulp build' and npm build both.. it fails as shown below.

> node_modules/gulp/bin/gulp.js build

module.js:338
    throw err;
          ^
at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/ginahagg/mywork/subrosa/subrosa-client/node_modules/del/node_modules/globby/index.js:2:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "run-script" "build"
npm ERR! node v0.12.0
npm ERR! npm  v2.6.0
npm ERR! code ELIFECYCLE
npm ERR! subrosa-client@1.3.0 build: `node_modules/gulp/bin/gulp.js build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the subrosa-client@1.3.0 build script 'node_modules/gulp/bin/gulp.js build'.
npm ERR! This is most likely a problem with the subrosa-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node_modules/gulp/bin/gulp.js build
npm ERR! You can get their info via:
npm ERR!     npm owner ls subrosa-client
npm ERR! There is likely additional logging output above.

Error: Cannot find module 'array-union'
